/*
Author: Radwa Ahmed Abd-Elsattar
Module: SPI_Integration_tb
Modelling: RTL
Description: Integration Testbench for SPI Master and Wrapper Slave
*/

module SPI_Integration_tb;

// Global signals
reg Clk;
reg Rst_n;

// Master control signals
reg Start;
reg  [10-1:0] tx_data;
wire [10-1:0] rx_data;
wire master_busy;
wire master_done;

// Inter-connection signals
wire MISO;
wire MOSI;
wire SCLK;
wire CS_n;

// Instantiate SPI Master (using the updated spi_master included above)
spi_master #(.DATA_WIDTH(10), .CLK_DIV(2)) master_U1 (
    .clk(Clk), 
    .rst_n(Rst_n), 
    .start(Start), 
    .MISO(MISO), 
    .tx_data(tx_data), 
    .MOSI(MOSI), 
    .SCLK(SCLK), 
    .cs_n(CS_n), 
    .rx_data(rx_data), 
    .busy(master_busy), 
    .done(master_done)
);

// Instantiate SPI Wrapper Slave
wrapper_slave #(.mem_depth(256), .addr_width(8), .data_width(8)) slave_U1 (
    .mosi(MOSI),
    .miso(MISO),
    .ss_n(CS_n),     // Connected directly to Master's cs_n
    .clk(SCLK),      // Connected to SPI Clock generated by Master
    .rstn(Rst_n)
);

// Clock Generation (100MHz master system clock)
always #5 Clk = ~Clk;

initial begin
    // Initialize Signals
    Clk     = 0;
    Rst_n   = 0; 
    Start   = 0;
    tx_data = 10'd0;

    // Reset Sequence
    #30;
    Rst_n = 1;
    #20;

    // ==================================================
    // Step 1: Write Address Command (Opcode: 00)
    // Send Write Address = 8'hAA (8'b10101010)
    // ==================================================
    $display("\n[TB] --- Step 1: Sending Write Address (0xAA) ---");
    tx_data = 10'b00_10101010;

    @(posedge Clk);
    Start = 1'b1;
    @(posedge Clk);
    Start = 1'b0;

    // Wait for transaction to complete
    @(posedge master_done);
    $display("[TB] Step 1 Completed (Address Loaded in Slave)");
    // Extra delay to ensure slave processes completely
    repeat(10) @(posedge Clk);

    // ==================================================
    // Step 2: Write Data Command (Opcode: 01)
    // Send Data to write = 8'h55 (8'b01010101)
    // ==================================================
    $display("\n[TB] --- Step 2: Sending Write Data (0x55) ---");
    tx_data = 10'b01_01010101;

    @(posedge Clk);
    Start = 1'b1;
    @(posedge Clk);
    Start = 1'b0;

    @(posedge master_done);
    $display("[TB] Step 2 Completed (Data Written to RAM)");
    // Extra delay to ensure slave processes completely
    repeat(10) @(posedge Clk);

    // ==================================================
    // Step 3: Read Address Command (Opcode: 10)
    // Send Read Address = 8'hAA (8'b10101010)
    // ==================================================
    $display("\n[TB] --- Step 3: Sending Read Address (0xAA) ---");
    tx_data = 10'b10_10101010;

    @(posedge Clk);
    Start = 1'b1;
    @(posedge Clk);
    Start = 1'b0;

    @(posedge master_done);
    $display("[TB] Step 3 Completed (Read Address Loaded in Slave)");
    // Extra delay to ensure slave processes completely
    repeat(10) @(posedge Clk);

    // ==================================================
    // Step 4: Read Data Command (Opcode: 11)
    // Master sends Dummy bits, Slave responds with Data on MISO
    // ==================================================
    $display("\n[TB] --- Step 4: Requesting Read Data from Slave ---");
    tx_data = 10'b11_00000000; // Dummy frame

    @(posedge Clk);
    Start = 1'b1;
    @(posedge Clk);
    Start = 1'b0;

    @(posedge master_done);
    repeat(20) @(posedge Clk); // Extra settling delay
    
    // Automatic Verification
    $display("[TB] Received Data from Slave: 0x%h (Raw Frame: 10'b%b)", rx_data[7:0], rx_data);
    
    if (rx_data[7:0] == 8'h55) begin
        $display("[TB] ========================================");
        $display("[TB] SUCCESS: Read Data matches Written Data (0x55)!");
        $display("[TB] All Four Cases Passed Successfully!");
        $display("[TB] ========================================\n");
    end else begin
        $display("[TB] ========================================");
        $display("[TB] ERROR: Expected 0x55, but received 0x%h", rx_data[7:0]);
        $display("[TB] ========================================\n");
    end

    #50;
    $display("Test Completed!");
    $finish;
end

// Monitor for debug visibility
initial begin
    $monitor("[%0t ns] Start=%b Done=%b Busy=%b | MOSI=%b MISO=%b SCLK=%b CS_n=%b | RX_Data=0x%h TX_Data=0x%h", 
             $time, Start, master_done, master_busy, MOSI, MISO, SCLK, CS_n, rx_data, tx_data);
end

endmodule
